version: '3.8'

services:
  sentryn-redis:
    image: redis:7.2-alpine
    container_name: sentryn-redis
    command: redis-server --protected-mode no
    ports:
      - "0.0.0.0:6379:6379"
    restart: always

  sentryn-qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: sentryn-qdrant
    ports:
      - "0.0.0.0:6333:6333"
      - "0.0.0.0:6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: always
